---
services:
  elastic:
    image: elasticsearch:5.4
    ports:
     - "9200:9200"
    volumes:
     - /sites/dev/python/api-elastic-search/.data/elasticsearch/usr/share/elasticsearch/data:/usr/share/elasticsearch/data
  php:
    image: "phalconphp/php-fpm:7-min"
    volumes:
      - ./www/:/var/www/html
    environment:
      # API: 'http://10.70.2.30:9200'
      API: 'http://elastic:9200'
  web:
    image: "nginx:latest"
    mem_limit: 96m
    ports:
      - "80:80"
    volumes:
      - "./config/nginx/:/etc/nginx/conf.d/"
      - "./.data/nginx/logs:/var/log/nginx/"

version: "2"
