---
services:
  db:
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=eloquent
      - MYSQL_USER=root
    image: "mysql:5.7"
    volumes:
      - "./.data/server/mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
  php:
    build: "etc"
    mem_limit: 500m
    volumes:
      - "./:/var/www/html"
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
  web:
    image: "nginx:latest"
    mem_limit: 96m
    ports:
      - "80:80"
    volumes:
      - ".:/var/www/html"
      - "./etc/nginx/:/etc/nginx/conf.d/"
      - "./.data/server/nginx/nginx/logs:/var/log/nginx/"
version: "2"
