version: "3"
services:
  fakes3:
    image: lphoward/fake-s3
    ports:
      - "4569:4569"
    volumes:
      - ".data/fakes3:/fakes3/data"
    volumes:
      - .data/s3:/fakes3_root
  
  php:
    image: bhcosta90/php:7.4-dev
    volumes:
      - ./:/var/www/html/public
    ports:
      - "80:80"
    environment:
      - S3_BUCKET_NAME=testbucket
      - AWS_SECRET_ACCESS_KEY=fake
      - AWS_ACCESS_KEY_ID=alsofake
      - SQS_QUEUE_NAME=testqueue
      - SQS_REGION=us-west-2
      - SQS_SECURE=False
      - SQS_PORT=9324
