version: '2'
services:
  web:
    volumes:
      - ./app:/app
      - ./.tmp:/tmp
    ports:
      - "80:80"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: flask run --host=0.0.0.0 --port=80