version: "2"
services:
  db:
     env_file:
       - .env
     image: "mysql:5.7"
     volumes:
       - "./data/server/mysql:/var/lib/mysql"
     ports:
       - "3306:3306"
  apigility:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "80:80"
    volumes:
     - .:/var/www
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - db
      environment:
        PMA_HOST: db
        PMA_PORT: 3306
      ports:
        - '9000:80'