---
services:
  fakes3:
    image: lphoward/fake-s3
    ports:
      - "4569:4569"
    volumes:
      - "./data:/fakes3/data"
  php:
    build: "."
    mem_limit: 500m
    volumes:
      - "./:/var/www/html"
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
  web:
    image: "nginx:latest"
    mem_limit: 96m
    ports:
      - "80:80"
    volumes:
      - ".:/var/www/html"
      - "./etc/nginx/:/etc/nginx/conf.d/"
      - "./data/server/nginx/nginx/logs:/var/log/nginx/"
version: "2"
